services:
  - type: web
    name: fuzzy-oracle-streamlit
    env: python
    region: oregon
    branch: master
    rootDirectory: meu_projeto_streamlit   # Rodar comandos a partir desta pasta
    buildCommand: |
      apt-get update && \
      apt-get install -y libaio1 && \
      wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basic-linux.x64-21.8.0.0.0.zip && \
      unzip instantclient-basic-linux.x64-21.8.0.0.0.zip -d /usr/lib/oracle && \
      rm instantclient-basic-linux.x64-21.8.0.0.0.zip && \
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: DB_DSN
        fromSecret: DB_DSN
