services:
  - type: web
    name: fuzzy-oracle-streamlit
    env: python
    region: oregon
    branch: master
    rootDirectory: meu_projeto_streamlit
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: DB_DSN
        fromSecret: DB_DSN
